# Generated by Django 4.1.1 on 2022-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen_rider',
            name='Arearider',
            field=models.CharField(choices=[('Utara', 'Semarang Utara'), ('Barat', 'Semarang Barat'), ('Ngaliyan', 'Ngaliyan'), ('Tugu', 'Tugu'), ('Mijen', 'Mijen')], max_length=30),
        ),
    ]
