# Generated by Django 4.1.1 on 2022-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_absen_rider_arearider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen_rider',
            name='Tanggal_absen',
            field=models.DateField(auto_now=True),
        ),
    ]
