# Generated by Django 4.1.1 on 2022-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencaptain',
            name='J_hold',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
