# Generated by Django 4.0.4 on 2022-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_absencaptain_j_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencaptain',
            name='Tanggal_absen',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='absenfl_staff',
            name='Tanggal_absen',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='absenstaff',
            name='Tanggal_absen',
            field=models.DateField(auto_now_add=True),
        ),
    ]
