# Generated by Django 4.0.4 on 2022-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_absencaptain_tanggal_absen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji',
            name='asuransi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaji',
            name='lembur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaji',
            name='p_miss',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaji',
            name='p_qr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gaji',
            name='parkir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
