# Generated by Django 4.1.1 on 2022-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gaji_asuransi_gaji_lembur_gaji_p_miss_gaji_p_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaji',
            name='Tanggal_absen',
            field=models.DateField(auto_now=True),
        ),
    ]
