# Generated by Django 4.1.1 on 2022-10-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gaji_tanggal_absen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaji',
            name='username',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
