# Generated by Django 4.1.1 on 2022-10-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gaji_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaji',
            name='asuransi',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='lembur',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='p_miss',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='p_qr',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaji',
            name='parkir',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
